services:
  vegapunk-edison-bot-ticketing:
    container_name: vegapunk-edison-bot-ticketing
    image: muhfalihr/vegapunkedison-bot-ticketing:latest
    restart: unless-stopped
    volumes:
      - /path/to/config.yml:/vegapunk-app/config.yml
    networks:
      - vegapunk-network

networks:
  vegapunk-network:
    driver: bridge
