apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vegapunk-edison-database
spec:
  capacity:
    storage: 200Gi
  nfs:
    server: {{ .Values.mysql.volume.server }}
    path: {{ .Values.mysql.volume.path }}
  accessModes:
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: {{ .Values.namespace }}
    name: pvc-vegapunk-edison-database
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.2
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vegapunk-edison-database
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-vegapunk-edison-database
  storageClassName: ''
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
          volumeMounts:
            - name: main-data
              mountPath: /var/lib/mysql
          imagePullPolicy: IfNotPresent
      volumes:
        - name: main-data
          persistentVolumeClaim:
            claimName: pvc-vegapunk-edison-database
